FROM pytorch/pytorch:2.9.0-cuda13.0-cudnn9-devel

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

RUN apt-get update && apt-get install -y \
    --no-install-recommends \
    ffmpeg \
    git \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    && rm -rf /var/lib/apt/lists/*

COPY  ./docker/train.txt /tmp/
RUN pip install --no-cache-dir -r /tmp/train.txt

WORKDIR /app
ENTRYPOINT [ "/bin/bash" ]
