components:
  model:
    type: DfineDetecor
    components:
      backbone:
        type: HGNetV2
        params:
          name: 'B4'
          return_idx: [1, 2, 3]
          freeze_at: 0
          freeze_stem_only: True
          freeze_norm: True
      
      encoder:
        type: DfineEncoder

      decoder:
        type: DfineDecoder


  optimizer:
    type: adamw
    params:
      lr: 0.00025
      betas: [0.9, 0.999]
      weight_decay: 0.000125
      pgassignment:
        -
          pattern: '^(?=.*backbone)(?!.*norm|bn).*$'
          lr: 0.0000125
        -
          pattern: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
          weight_decay: 0.


  