components:
  model:
    type: DfineDetecor
    components:
      backbone:
        type: HGNetV2
        params:
          name: 'B0'
          return_idx: [1, 2, 3]
          freeze_at: -1
          freeze_norm: False
          use_lab: True
      
      encoder:
        type: DfineEncoder
        params:
          feat_strides: [8, 16, 32]
          in_channels: [256, 512, 1024]
          hidden_dim: 256
          depth_mult: 0.34
          expansion: 0.5

      decoder:
        type: DfineDecoder
        params:
          feat_channels: [256, 256, 256]
          num_layers: 3  
          eval_idx: -1  
          num_points: [3, 6, 3]

  optimizer:
    type: adamw
    params:
      lr: 0.0002
      betas: [0.9, 0.999]
      weight_decay: 0.1
      pgassignment:
        -
          pattern: '^(?=.*backbone)(?!.*norm|bn).*$'
          lr: 0.0001
        -
          pattern: '^(?=.*backbone)(?=.*norm|bn).*$'
          lr: 0.0001
          weight_decay: 0.
        -
          pattern: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
          weight_decay: 0.
